FROM 127.0.0.1:4000/kollaglue/ubuntu-source-nova-base:latest
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN apt-get install -y --no-install-recommends \
        qemu-utils \
        ceph-common \
    && apt-get clean \
    && mkdir -p /etc/ceph

    


