nginx:
  build: "nginx"
  ports:
    - "5000:5000"
  links:
    - registryv1:registryv1
    - registryv2:registryv2
registryv1:
  image: registry:0.9.1
  ports:
    - "5000"
registryv2:
  build: "../../"
  ports:
    - "5000"
